# Generated by Django 4.0.4 on 2022-05-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='time_field',
            field=models.DateTimeField(default='2022-5-19', verbose_name='Дата'),
        ),
    ]
