# Generated by Django 4.0.4 on 2022-05-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_manager', '0004_remove_todomodel_time_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AddField(
            model_name='todomodel',
            name='time_field',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
    ]
