# Generated by Django 4.0.4 on 2022-05-18 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_manager', '0006_alter_todomodel_time_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='todo_post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='todo_manager.todomodel', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
