# Generated by Django 4.0.4 on 2022-05-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_manager', '0007_comments_todo_post_alter_comments_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='time_field',
            field=models.DateField(default='2022-5-19', verbose_name='Дата'),
        ),
    ]
