# Generated by Django 4.0.4 on 2022-05-18 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_manager', '0009_alter_todomodel_time_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='time_field',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата'),
        ),
    ]
