# Generated by Django 4.0.4 on 2022-05-18 17:56

from django.db import migrations, models
import todo_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_manager', '0010_alter_todomodel_time_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='time_field',
            field=models.DateTimeField(default=todo_manager.models.get_date, verbose_name='Дата'),
        ),
    ]
